# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/keyur/Documents/Vivado/FlappyBird/FlappyBird.srcs/sources_1/ip/bird/bird.xci
# IP: The module: 'bird' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/keyur/Documents/Vivado/FlappyBird/FlappyBird.gen/sources_1/ip/bird/bird_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bird'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/keyur/Documents/Vivado/FlappyBird/FlappyBird.srcs/sources_1/ip/bird/bird.xci
# IP: The module: 'bird' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/keyur/Documents/Vivado/FlappyBird/FlappyBird.gen/sources_1/ip/bird/bird_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bird'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
